spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/userdb?serverTimezone=Europe/Paris
    username: root
    password: rootroot
  application:
    name: apigateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
springdoc:
  swagger-ui:
    path: /api-docs
