spring:
  r2dbc:
    url: r2dbc:mysql://host.docker.internal:3306/userdb?serverTimezone=Europe/Paris # for prod
    #url: r2dbc:mysql://localhost:3306/userdb?serverTimezone=Europe/Paris # for dev
    username: root
    password: rootroot
  application:
    name: apigateway
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8083/eureka #for prod
      #defaultZone: http://localhost:8083/eureka #for dev
debug: true