spring:
  data:
    mongodb:
      host: host.docker.internal #for prod
      #host: localhost #for dev
      port: 27017
      database: PatientNotedb
  application:
    name: riskmanager
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8083/eureka #for prod
      #defaultZone: http://localhost:8083/eureka #for dev
