spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: PatientNotedb
  application:
    name: riskmanager
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8083/eureka
