spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patienttest
    username: root
    password: rootroot
  application:
    name: patientmanager
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG